# Configures yarn for eagle-print repo

# Note on afterInstall This performs 3 main tasks: -
#  1. runs all patches
#  2. runs prepare script to install husky hooks
#  3. installs all additional-modules
# and can have different behaviours based on the value of
# $env:SKIP_AFTER_INSTALL which is a comma separated list made up of the following values: -
#   patch-package (to skip step 1)
#   prepare (to skip step 2)
#   additional-modules (to skip step 3)
# it will run all the steps that are not in the list.
# There is also a special value of "all" which will run none of the steps.
#
# We primarily use this as part of grunt package, or in CI builds where we want to only
# install modules for grunt-tasks.
afterInstall: node ./scripts/after_install.js

nodeLinker: node-modules

npmAlwaysAuth: true

# We set this as an environment variable in developers' machines, and also
# as a parameter on teamcity.
npmAuthToken: '${ARTIFACTORY_NPM_TOKEN}'

npmRegistryServer: 'https://artifactory.grabcad.net/artifactory/api/npm/npm-repo'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: ./.yarn/yarn-3.8.2.js
