# Configures yarn for Yarn3
nodeLinker: node-modules

npmAlwaysAuth: true

# We set this as an environment variable in developers' machines, and also
# as a parameter on teamcity.
npmAuthToken: '${ARTIFACTORY_NPM_TOKEN}'

npmRegistryServer: 'https://artifactory.grabcad.net/artifactory/api/npm/npm-repo'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: ./.yarn/yarn-3.8.2.js
